### ISSUE TITLE
Set up Styled-Components

### ISSUE THREAD

**Issue by sdmungov** [Model-UN/cimun-web#19]
**Description**
We need to create a styles folder that contains a colors and fonts folder that contains our different font choices and color palette that we can reference in our components and pages for creating consistent styling across site

**UC**
* As a user, I want to see visually appealing and consistent styling across entire website in order to not be confused and jarred with drastically different styling on each page I visit on the same site
* As a developer, I want to easily access, view, and change styling across components in order to save time when implementing styling or changing a color/font choice across site

**AC**
* Both of these files should simply export default a list of fonts or colors
* colors file should contain a list of items as such "descriptiveColorTitle: "#hexcode", "
* fonts file should contain a list of items as such "descriptiveFontName: "font-family", "
* install styled-components into the repo
* set up some basic reusable tags in containers folder and typography folder

**Comment by FB-Reda** [comment]
Oh wait @sdmungov are we planning on utilizing anything like [styled-components](https://styled-components.com)

**Comment by sdmungov** [comment]
> Oh wait @sdmungov are we planning on utilizing anything like [styled-components](https://styled-components.com)

@FB-Reda I have used styled components a lot in my mobile projects so I am definitely down to use it here if we both enjoy it

**Comment by FB-Reda** [comment]
I'm an enjoyer of it, but down to use whatever you find optimal.

**Comment by sdmungov** [comment]
perfect, I think its a good idea since we both like to partake in styled-components

**Comment by sdmungov** [comment]
so amended to this ticket i will add styled components into the repo
