### ISSUE TITLE
Finalize Jumbotron's Background Image

### ISSUE THREAD

**Issue by sdmungov** [Model-UN/cimun-web#23]
**Description**
Choose which license free image we are using for the background to the jumbotron component. 

**UC**
* As a user, I want to see a relevant optimized background image that the text shows clearly on in order to get a good first impression of the site and the conference as a whole. 
* As a user, I want to see the jumbotron be displayed without delay to load the svg image in order to see site content right away instead of a blank screen for the first second after landing on site

**AC**
* Choose image that is license free
* Export image as svg file type
* Optimize svg file with SVGOMG and svg2jsx or equivalent service

**Comment by FB-Reda** [comment]
If you have a specific shot in mind we can send someone (probably me) to go downtown and take a pic.  Hotel walkthrough is coming up so that's another opportunity.
