### ISSUE TITLE
Break down and create landing page enhancement issues

### ISSUE THREAD

**Issue by he-james** [Model-UN/cimun-web#9]
**Blocked By**: #8 #7 #4

**Description**
As designs are further enhanced, there will be a better idea on relevant information to add to the landing page. Break these down and create focused user stories to turn into issues. Not doing this will be a real problem, since a broad issue created out of ignorance of scope would be horrible to develop, and creation of many focused issues that are _not relevant to development or the users' need_ would also be horrible and confusing.

**UC**
* **As an** engineer, **I want to** work on focused tickets that are relevant to the needs specified on this project **in order to** write good code and understand the value of the issue that I am working on.

**AC**
* Issues created must all follow the format provided in #5
* Issues created must all be assigned to the "CIMUN Homepage" milestone
* Issues created must have relevant labels (e.g. "Enhancement"), if there are no relevant labels, create one.
* Issues should indicate the flow of work with a "Blocked By" field, if needed. It would also be nice to add a "Blocks" field, but that is less important since "Blocked By" allows engineers to check on whether the flow of work has been completed up to that point, rather than the other way around.

**Comment by sdmungov** [comment]
@he-james please look over the tickets I just created that break down the component building blocks that make up the home page to make sure they look good and cover the AC so that this issue can be closed
